* Navam Shrivastav 2019A7PS0092H
* Sukrit Kumar 2019AAPS0231H
* Shrikrishna Lolla 2019AAPS0345H

In [1]:
import numpy as np
import pandas as pd 
import networkx as nx

In [2]:
def getAdjacencyMatrix():
    """
    Returns the adjacency matrix for a given user inputted graph
    with n nodes e edges each user defined
    """
    n = int(input("Enter no of nodes in the graph "))
    e = int(input("Enter no of edges in the graph "))
    adj = np.zeros(shape=(n,n))
    for i in range(e):
        edge = input()
        i,j = edge.split(",")
        adj[int(i)-1,int(j)-1] = 1
    return adj

In [3]:
def convert_adj_to_prob(adj_matrix, teleport=0.0):
    """
    Converts a given adjacency matrix to a probability translation matrix
    Inputs:
    Adjacency Matrix
    teleport probability (alpha)
    """
    n = adj_matrix.shape[0]
    prob_matrix = np.zeros((n, n))
    row_sum = np.sum(adj_matrix, axis=1)
    teleport_prob = teleport / n
    # convert adjacency matrix to prob matrix
    for i in range(n):
        for j in range(n):
            if adj_matrix[i, j] == 1:
                prob_matrix[i, j] = ((1-teleport)*adj_matrix[i, j]) / (row_sum[i]) + teleport_prob
            else:
                prob_matrix[i, j] = teleport_prob
    return prob_matrix

In [4]:
P = [[1/6,2/3,1/6],[5/12,1/6,5/12],[1/6,2/3,1/6]]

In [5]:
adj = [[0,1,0],[1,0,1],[0,1,0]]

In [6]:
test_P = convert_adj_to_prob(np.array(adj),0.5)

In [7]:
np.isclose(test_P,np.array(P))

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [13]:
# Calculation of steady state left eigen vector using the numpy 
def getLeftEigenVector(P):
    """
    Compute the left eigen vector for a given probability translation matrix using numpy
    """
    values, Vector = np.linalg.eig(np.array(P).T)
    left_vec = Vector[:, np.argmax(values)].T
    left_vec_norm = (left_vec/left_vec.sum()).real
    return left_vec_norm

In [14]:
# Run for a max no of iterations
def power_iteration_iter(prob_matrix, max_iter=100):
    """
    Compute the left eigen vector using the power iteration method
    Inputs: prob_matrix
    max_iters (optional) defaults to 100
    """
    n = prob_matrix.shape[0]
    eigen_vector = np.zeros(n)
    eigen_vector[0] = 1
    for i in range(max_iter):
        eigen_vector = prob_matrix.T.dot(eigen_vector)
        eigen_vector = eigen_vector/np.sum(eigen_vector)
    return eigen_vector

In [15]:
# Or run until numpy considers them to be close enough
def power_iteration(prob_matrix):
    """
    Compute the left eigen vector using the power iteration method, this method runs as long as the previous computed value is not close to the newest computed value
    this is checked using the np.isclose() command
    Inputs: prob_matrix
    """
    n = prob_matrix.shape[0]
    eigen_vector = np.zeros(n)
    eigen_vector[0] = 1
    eigen_vector_prev = eigen_vector
    while True:
        eigen_vector_prev = eigen_vector
        eigen_vector = prob_matrix.T.dot(eigen_vector)
        eigen_vector = eigen_vector/np.sum(eigen_vector)
        if np.isclose(eigen_vector,eigen_vector_prev).all():
            break;
    return eigen_vector

In [16]:
def pageRank(G,alpha,iters= 0):
  adj = nx.adjacency_matrix(G).todense()
  P  = convert_adj_to_prob(np.array(adj),alpha)
  if iters != 0:
    return power_iteration_iter(P,iters)
  return getLeftEigenVector(P)

In [17]:
result = getLeftEigenVector(test_P) # using numpy
result

array([0.27777778, 0.44444444, 0.27777778])

In [18]:
result = power_iteration(test_P) # using power iteration till convergence
result

array([0.27777735, 0.44444529, 0.27777735])

In [19]:
result = power_iteration_iter(test_P,100) # using power iteration for a fixed no of iterations
result

array([0.27777778, 0.44444444, 0.27777778])

In [16]:
sorted_res = sorted(result,reverse=True)
sorted_idx = np.argsort(result)[-3:] # get index of 3 highest scores
rev_pos = 3
for idx in sorted_idx:
    print(f"{rev_pos} highest pagerank score is with index {idx}")
    rev_pos = rev_pos -1
sorted_res

3 highest pagerank score is with index 2
2 highest pagerank score is with index 0
1 highest pagerank score is with index 1


[0.4444444444444445, 0.27777777777777785, 0.27777777777777773]

In [ ]:
ad = getAdjacencyMatrix()
pr = convert_adj_to_prob(ad,0.5)
power_iteration(pr)